import type { Metadata } from "next";
import "../../assets/css/plugins/bootstrap.min.css";
import "../../assets/css/plugins/cookit.min.css";
import "../../assets/css/plugins/gdpr-cookie.css";
import "../../assets/css/plugins/jaralux.min.css";
import "../../assets/css/plugins/jquery-ui.min.css";
import "../../assets/css/plugins/magnific-popup.css";
import "../../assets/css/plugins/meanmenu.css";
import "../../assets/css/plugins/nice-select.css";
import "../../assets/css/plugins.min.css";
import "../../assets/fonts/flaticon_bokinn.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/scrollbar";
import "swiper/swiper-bundle.css";
import "../../assets/css/style.css";
import "react-datepicker/dist/react-datepicker.css";
import 'aos/dist/aos.css';
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Moonlit - Hotel and Resturant NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Script src="/assets/js/smoothscroll.js" strategy="afterInteractive"/>
      </body>
    </html>
  );
}
